In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from google.colab import files

uploaded = files.upload()
data_read = pd.read_excel('shooping_demo.xls')
data_read.head()

Saving shooping_demo.xls to shooping_demo.xls

       Day Discount Free Delivery  Buy
0  Weekday      Yes           Yes  Yes
1  Weekday      Yes           Yes  Yes
2  Weekend       No            No   No
3  Holiday      Yes           Yes  Yes
4  Weekday      Yes           Yes  Yes

In [2]:
data_read.shape

(50, 4)

In [3]:
data_read['Buy'].value_counts()

Buy
Yes    41
No      9
Name: count, dtype: int64

In [4]:
pYes = 24/30
pNo = 6/30

In [5]:
print(pYes)

0.8

In [6]:
print(pNo)

0.2

In [7]:
pd.crosstab(data_read['Day'], data_read['Buy'])

Buy      No  Yes
Day
Holiday   6   18
Weekday   2    9
Weekend   1   14

In [8]:
BHolidayNo = 6/6
BWeekdayNo = 2/6
BWeekendNo = 1/6

BHolidayYes = 18/24
BWeekdayYes = 9/24
BWeekendYes = 14/24

BHoliday = 24/30
BWeekday = 11/30
BWeekend = 15/30

print(BWeekdayYes)

0.375

In [9]:
# P(A|B) ?
# P(B) = BWeekday
# P (A) = No Buy
# p(B|A) = P Weekend/No Buy

In [10]:
pNoWeekday = (BWeekdayNo*pNo)/BWeekday
print(pNoWeekday)

0.18181818181818182

In [11]:
pYesweekday = (BWeekdayYes*pYes)/BWeekday
print(pYesweekday)

0.8181818181818183

In [12]:
# probabilitas (Buy| Weekday) > dibanding dengan probabilitas (NoBuy | Weekday)
print(pNoWeekday)
print(pYesweekday)

0.18181818181818182
0.8181818181818183

In [13]:
# kondisi B dimana
# day = Holiday
# Discount = Yes
# Free Delivery = Yes
# A =NoBuy
# P(A|B) = P(NoBuy|discountYes, Free Delivery Yes, PDayHoliday)

In [14]:
pd.crosstab(data_read['Discount'], data_read['Buy'])

Buy       No  Yes
Discount
No         5   12
Yes        4   29

In [15]:
pNoDiscountNo = 5/6
pYesDiscountNo = 4/6

pNoDiscountYes = 12/24
pYesDiscountYes = 29/24

pNoDiscount = 17/30
pYesdiscount = 33/30

In [16]:
pd.crosstab(data_read['Free Delivery'], data_read['Buy'])

Buy            No  Yes
Free Delivery
No              4   10
Yes             5   31

In [17]:
pNoDeliveryNo= 4/6
pYesDeliveryNo= 5/6

pNoDeliveryYes = 10/24
pYesDeliveryYes = 31/24

pNodelivery = 14/30
pYesDelivery = 36/30

In [18]:
#Kondisi B dimana

# Day Holiday

#Discount = Yes

#Free Delivery = Yes
#P(A) NoBuy = PNo
#P(B) pYesDiscount, pYes Delivery, BHoliday
#P(B/A)1 (BHoliday No Buy) BHoliday No
#P(B/A)2 = (pYesDiscount No Buy) = pYesDiscountNo
#P(B/A)3 = (pYesDelivery No Buy) = pYesDeliveryNo
#P(B)1 BHoliday
#P(B)2 pYesDiscount
#P(B)3 pYesDelivery
#ditanyakan P(A/B) ?
#Rumus
#P(A/B) = P(B|A)*P(A)/P(B)

In [19]:
pNoBuy1 = ((BHolidayNo*pYesDiscountNo*pYesDeliveryNo)*pNo)/(BHoliday*pYesdiscount*pYesDelivery)
print(pNoBuy1)

0.10521885521885523

In [20]:
#Kondisi B dimana
#Day Holiday
#Discount = Yes
#Free Delivery = Yes
#P(A) Buy = pYes
#P(B) pYes Discount, pYes Delivery, BHoliday
#P(B|A)1 (BHoliday Buy) = BHolidayYes
#P(B/A)2 (pYesDiscount Buy) pYesDiscountYes
#P(B|A)3 = (pYesDelivery Buy) = pYesDeliveryYes I
#P(B)1 BHoliday
#P(B)2 pYesDiscount
#P(B)3 pYesDelivery

#ditanyakan P(A/B) ?
#Rumus
#P(A/B) = P(B|A)*P(A)/P(B)

In [21]:
pBuy2 = ((BHolidayYes*pYesDiscountYes*pYesDeliveryYes)*pYes)/(BHoliday*pYesdiscount*pYesDelivery)
print (pBuy2)

0.8867976641414141

In [22]:
# probablity of no buy = 0.10521885521885523
# probablity of buy = 0.8867976641414141

In [23]:
pSum = pNoBuy1+pBuy2
print(pSum)

0.9920165193602694

In [24]:
pBuy = pBuy2/pSum *100
print(pBuy)

89.39343718926087

In [25]:
pNoBuy = (pNoBuy1*pSum) *100
print(pNoBuy)

10.437884252528088